name: GitHub Metrics

on:
  schedule: [{cron: "0 */12 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.svg
          
          # Remove o cabeçalho padrão (que traz a foto e seguidores)
          base: ""
          
          # Adiciona um título customizado com o seu nome dentro do SVG
          plugin_introduction: yes
          plugin_introduction_title: Laura Morgado

          # Módulo de Estatísticas (Commits, PRs, Estrelas, Repositórios)
          plugin_lines: yes
          plugin_notable: yes
          
          # Módulo de Linguagens 
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 6
    

          # Estilização e Cores em Roxo/Dark
          style_preset: markdown
          extras_css: |
            svg {
              background-color: #0d1117 !important;
              color: #c9d1d9 !important;
            }
            .fill-primary { fill: #a855f7 !important; }
            .text-primary { color: #a855f7 !important; }
            .field { color: #a855f7 !important; }
